apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: filecountwatchers.count-watcher-operator.com
spec:
  group: count-watcher-operator.com
  names:
    kind: FileCountWatcher
    plural: filecountwatchers
    singular: filecountwatcher
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              dir:
                type: string
